package flexboxorderordersystem;
/**
 * @author UP687776
 */

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class PresentationFrame extends javax.swing.JFrame {
    private final ArrayList<BoxTypes> boxes;
    
    /**
     * Creates new form PresentationFrame
     * @param boxes
     */
    public PresentationFrame(ArrayList<BoxTypes> boxes) {
        this.boxes = boxes;
        // orderItems = new ArrayList<>();
        //super("Flexbox Ordering System");
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReinForcedBottom = new javax.swing.ButtonGroup();
        ReinforcedCorner = new javax.swing.ButtonGroup();
        SealTop = new javax.swing.ButtonGroup();
        ColouType = new javax.swing.ButtonGroup();
        BoxTypes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        FlexBoxTitleLabe = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SizeLabel = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        width = new javax.swing.JTextField();
        length = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        AdditionalFuncLabel = new javax.swing.JLabel();
        reinBottomLabel = new javax.swing.JLabel();
        reinCornerLabel = new javax.swing.JLabel();
        sealTopLabel = new javax.swing.JLabel();
        reinforcedBottomYes = new javax.swing.JRadioButton();
        reinforcedBottomNo = new javax.swing.JRadioButton();
        reinforcedCornerYes = new javax.swing.JRadioButton();
        reinforcedCornerNo = new javax.swing.JRadioButton();
        sealTopYes = new javax.swing.JRadioButton();
        sealTopNo = new javax.swing.JRadioButton();
        quantity = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BoxTypeLabel = new javax.swing.JLabel();
        boxType1 = new javax.swing.JRadioButton();
        boxType2 = new javax.swing.JRadioButton();
        boxType3 = new javax.swing.JRadioButton();
        boxType4 = new javax.swing.JRadioButton();
        boxType5 = new javax.swing.JRadioButton();
        colourTypeLabel = new javax.swing.JLabel();
        colourType0 = new javax.swing.JRadioButton();
        colourType1 = new javax.swing.JRadioButton();
        colourType2 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        totalCost = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        quantityLabel2 = new javax.swing.JPanel();
        TotalCostLabel1 = new javax.swing.JLabel();
        TotalCostLabel = new javax.swing.JLabel();
        OrderDetailsLabel1 = new javax.swing.JLabel();
        quantityLabel1 = new javax.swing.JLabel();
        quantityLabel3 = new javax.swing.JLabel();
        Order1Label = new javax.swing.JLabel();
        OrderShow1 = new javax.swing.JLabel();
        ReinBottom = new javax.swing.JLabel();
        reinCorner = new javax.swing.JLabel();
        rcLabel = new javax.swing.JLabel();
        rbLabel = new javax.swing.JLabel();
        ST = new javax.swing.JLabel();
        stLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        OrderDetailsLabel = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        OrderDetailsLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 40));

        FlexBoxTitleLabe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        FlexBoxTitleLabe.setText("Flexbox Ordering System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(FlexBoxTitleLabe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FlexBoxTitleLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setForeground(new java.awt.Color(10, 10, 10));
        jPanel2.setToolTipText("");
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SizeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SizeLabel.setText("Size in cm");

        widthLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        widthLabel.setText("Width");

        lengthLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lengthLabel.setText("Length");

        heightLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        heightLabel.setText("Height");

        width.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthActionPerformed(evt);
            }
        });
        width.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                widthKeyTyped(evt);
            }
        });

        length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthActionPerformed(evt);
            }
        });
        length.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lengthKeyTyped(evt);
            }
        });

        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });
        height.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heightKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(SizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(SizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setToolTipText("");

        AdditionalFuncLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdditionalFuncLabel.setText("Additional Functionality");

        reinBottomLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reinBottomLabel.setText("Reinforced Bottom");

        reinCornerLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reinCornerLabel.setText("Reinforced Corner");

        sealTopLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sealTopLabel.setText("Sealable Top");

        ReinForcedBottom.add(reinforcedBottomYes);
        reinforcedBottomYes.setText("Yes");
        reinforcedBottomYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinforcedBottomYesActionPerformed(evt);
            }
        });

        ReinForcedBottom.add(reinforcedBottomNo);
        reinforcedBottomNo.setText("No");

        ReinforcedCorner.add(reinforcedCornerYes);
        reinforcedCornerYes.setText("Yes");
        reinforcedCornerYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinforcedCornerYesActionPerformed(evt);
            }
        });

        ReinforcedCorner.add(reinforcedCornerNo);
        reinforcedCornerNo.setText("No");
        reinforcedCornerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinforcedCornerNoActionPerformed(evt);
            }
        });

        SealTop.add(sealTopYes);
        sealTopYes.setText("Yes");

        SealTop.add(sealTopNo);
        sealTopNo.setText("No");

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                quantityKeyTyped(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quantityLabel.setText("Quantity");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sealTopLabel)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reinBottomLabel)
                            .addComponent(reinCornerLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(reinforcedBottomYes)
                                .addGap(18, 18, 18)
                                .addComponent(reinforcedBottomNo))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(reinforcedCornerYes)
                                    .addComponent(sealTopYes))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sealTopNo)
                                    .addComponent(reinforcedCornerNo))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdditionalFuncLabel)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(AdditionalFuncLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reinBottomLabel)
                    .addComponent(reinforcedBottomYes)
                    .addComponent(reinforcedBottomNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reinCornerLabel)
                    .addComponent(reinforcedCornerYes)
                    .addComponent(reinforcedCornerNo))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sealTopLabel)
                    .addComponent(sealTopYes)
                    .addComponent(sealTopNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setToolTipText("");

        BoxTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BoxTypeLabel.setText("Grade of Card");

        BoxTypes.add(boxType1);
        boxType1.setText("Card 1");
        boxType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxType1ActionPerformed(evt);
            }
        });

        BoxTypes.add(boxType2);
        boxType2.setText("Card 2");

        BoxTypes.add(boxType3);
        boxType3.setText("Card 3");

        BoxTypes.add(boxType4);
        boxType4.setText("Card 4");

        BoxTypes.add(boxType5);
        boxType5.setText("Card 5");
        boxType5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxType5ActionPerformed(evt);
            }
        });

        colourTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        colourTypeLabel.setText("Colour Type: 1 or 2");

        ColouType.add(colourType0);
        colourType0.setText("Colour Type 0");

        ColouType.add(colourType1);
        colourType1.setText("Colour Type 1");

        ColouType.add(colourType2);
        colourType2.setText("Colour Type 2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(boxType1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxType2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxType3)
                        .addGap(12, 12, 12)
                        .addComponent(boxType4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxType5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(BoxTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colourTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(colourType0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colourType1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(colourType2)
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(BoxTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxType1)
                    .addComponent(boxType2)
                    .addComponent(boxType3)
                    .addComponent(boxType4)
                    .addComponent(boxType5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(colourTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colourType0)
                    .addComponent(colourType1)
                    .addComponent(colourType2))
                .addGap(33, 33, 33))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel8.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel8.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flexboxorderordersystem/Java Image.PNG"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Hints");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel17))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        totalCost.setText("Add Box to Order");
        totalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCostActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.setPreferredSize(new java.awt.Dimension(152, 29));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        quit.setText("Quit");
        quit.setPreferredSize(new java.awt.Dimension(152, 29));
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        quantityLabel2.setBorder(new javax.swing.border.MatteBorder(null));

        TotalCostLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TotalCostLabel1.setText("Total Cost");

        TotalCostLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TotalCostLabel.setText("£0");

        OrderDetailsLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OrderDetailsLabel1.setText("Order Details");

        quantityLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quantityLabel1.setText("Quantity");

        quantityLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        quantityLabel3.setText("0");

        Order1Label.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        Order1Label.setText("Size");

        OrderShow1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        OrderShow1.setText("OrderShow");

        ReinBottom.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ReinBottom.setText("RB");

        reinCorner.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        reinCorner.setText("RC");

        rcLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rcLabel.setText("Y/N");

        rbLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        rbLabel.setText("Y/N");

        ST.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ST.setText("ST");

        stLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        stLabel.setText("Y/N");

        javax.swing.GroupLayout quantityLabel2Layout = new javax.swing.GroupLayout(quantityLabel2);
        quantityLabel2.setLayout(quantityLabel2Layout);
        quantityLabel2Layout.setHorizontalGroup(
            quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quantityLabel2Layout.createSequentialGroup()
                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quantityLabel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(OrderDetailsLabel1))
                    .addGroup(quantityLabel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalCostLabel1)
                            .addComponent(quantityLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityLabel3)
                            .addComponent(TotalCostLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(quantityLabel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(quantityLabel2Layout.createSequentialGroup()
                        .addComponent(Order1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OrderShow1)
                        .addGap(33, 33, 33))
                    .addGroup(quantityLabel2Layout.createSequentialGroup()
                        .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReinBottom)
                            .addComponent(reinCorner)
                            .addComponent(ST))
                        .addGap(130, 130, 130)
                        .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quantityLabel2Layout.createSequentialGroup()
                                .addComponent(stLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(quantityLabel2Layout.createSequentialGroup()
                                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbLabel)
                                    .addComponent(rcLabel))
                                .addContainerGap(64, Short.MAX_VALUE))))))
        );
        quantityLabel2Layout.setVerticalGroup(
            quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quantityLabel2Layout.createSequentialGroup()
                .addComponent(OrderDetailsLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalCostLabel1)
                    .addComponent(TotalCostLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Order1Label)
                    .addComponent(OrderShow1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReinBottom)
                    .addComponent(rbLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reinCorner)
                    .addComponent(rcLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(quantityLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ST)
                    .addComponent(stLabel))
                .addContainerGap())
        );

        jPanel10.setBorder(new javax.swing.border.MatteBorder(null));

        OrderDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OrderDetailsLabel)
                .addGap(83, 83, 83))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(OrderDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 207, Short.MAX_VALUE))
        );

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total", "Quantity", "RB", "RC", "ST"
            }
        ));
        jScrollPane1.setViewportView(table);

        OrderDetailsLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        OrderDetailsLabel2.setText("Multiple Orders");

        jMenu1.setText("Flexbox Ordering System");
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(totalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(quit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)))
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(quantityLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(OrderDetailsLabel2)
                                        .addGap(73, 73, 73)))
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator9)
                                    .addComponent(jSeparator7)
                                    .addComponent(jSeparator5)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(OrderDetailsLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(totalCost)
                                                        .addGap(36, 36, 36)
                                                        .addComponent(quit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(29, 29, 29)
                                                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(quantityLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthActionPerformed

    private void widthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthActionPerformed
        
    }//GEN-LAST:event_widthActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void reinforcedBottomYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinforcedBottomYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reinforcedBottomYesActionPerformed

    private void reinforcedCornerYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinforcedCornerYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reinforcedCornerYesActionPerformed

    private void reinforcedCornerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinforcedCornerNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reinforcedCornerNoActionPerformed
    
    /**
     * 
     * @param evt 
     * This hold all of the value and if statement conditions
     * It returns the total Cost of ordered box
     */
    
    private void totalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCostActionPerformed
        try {
            int userW = Integer.parseInt(width.getText());
            int userH = Integer.parseInt(height.getText());
            int userL = Integer.parseInt(length.getText());
            int userQ = Integer.parseInt(quantity.getText());
            boolean userCG1 = boxType1.isSelected();
            boolean userCG2 = boxType2.isSelected();
            boolean userCG3 = boxType3.isSelected();
            boolean userCG4 = boxType4.isSelected();
            boolean userCG5 = boxType5.isSelected();
            int cardGrade;
            
            if(boxType1.isSelected())
                cardGrade = 1;
            else if(boxType2.isSelected())
                cardGrade = 2;
            else if(boxType3.isSelected())
                cardGrade = 3;
            else if (boxType4.isSelected())
                cardGrade = 4;
            else if (boxType5.isSelected())
                cardGrade = 5;
            else
                cardGrade = 0;    
            if(cardGrade == 0)
                JOptionPane.showMessageDialog (null, "Please select a grade of card");
            
            boolean userCT0 = colourType0.isSelected();
            boolean userCT1 = colourType1.isSelected();
            boolean userCT2 = colourType2.isSelected();
            
            int colourType = 0;
            
            if(colourType0.isSelected())
                colourType = 0;

            else if(colourType1.isSelected())
                colourType = 1;
            else if(colourType2.isSelected())
                colourType = 2;
            else
                JOptionPane.showMessageDialog (null, "Please select a colour type");
            
            boolean userRBYes = reinforcedBottomYes.isSelected();
            boolean userRBNo = reinforcedBottomNo.isSelected();
            
            boolean reinBottom = false;
            
            if(reinforcedBottomYes.isSelected())
                reinBottom = true;
            else if(reinforcedBottomNo.isSelected())
                reinBottom = false;
            else
                JOptionPane.showMessageDialog (null, "Please select a reinforced bottom");
            
            boolean userRCYes = reinforcedCornerYes.isSelected();
            boolean userRCNo = reinforcedCornerNo.isSelected();
            
            boolean reinCorner = false;
            
            if(reinforcedCornerYes.isSelected())
                reinCorner = true;
            else if(reinforcedCornerNo.isSelected())
                reinCorner = false;
            else
                JOptionPane.showMessageDialog(null, "Please select a reinforced corner");
            
            boolean userSTYes = sealTopYes.isSelected();
            boolean userSTNo = sealTopNo.isSelected();
            
            boolean sealTop = false;

            boolean isValidBoxOrder = true;
            
            if(sealTopYes.isSelected())
                sealTop = true;
            else if(sealTopNo.isSelected())
                sealTop = false;
            else {
                JOptionPane.showMessageDialog (null, "Please select a sealTop");
                isValidBoxOrder = false;
            }
            
            if(userW <5 || userW >500){
                JOptionPane.showMessageDialog (null, "Please enter a width betwen 5 and 500");
                isValidBoxOrder = false;
            }
            if(userH <5 || userH>500) {
                JOptionPane.showMessageDialog (null, "Please enter a height betwen 5 and 500");
                isValidBoxOrder = false;
            }
            if(userL <5 || userL>500) {
                JOptionPane.showMessageDialog (null, "Please enter a length betwen 5 and 500");
                isValidBoxOrder = false;
            }
            if(userQ<1){
                JOptionPane.showMessageDialog (null, "Please enter 1 or more quantity");
                isValidBoxOrder = false;
            }
            
            int boxType = getBoxType(cardGrade, colourType, reinBottom, reinCorner);
            
            if(boxType == 0) {
                JOptionPane.showMessageDialog (null, "Invalid box type."
                        + " We  do not supply this type of Boxes");
                isValidBoxOrder = false;
            }
      
            if(isValidBoxOrder) {
                PriceCalculation priceCalculation = new PriceCalculation();
                double area = priceCalculation.area(userW, userL, userH); //getting the box area
                double basePrice = priceCalculation.calculateBoxBasePrice(area, cardGrade);
                double additionalPrice = priceCalculation.calculatBoxAdditionalsPrice(basePrice, colourType, reinBottom, reinCorner, sealTop);
                TotalCostLabel.setText(String.format("£%.2f", additionalPrice*userQ)); 
                OrderShow1.setText(" W " + Integer.toString(userW) +" + H  " + Integer.toString(userH) + "+ L " +  Integer.toString(userL));
                quantityLabel3.setText(Integer.toString(userQ));
                      
                rbLabel.setText(Boolean.toString(userRBYes == true || userRBNo == false ));
                rcLabel.setText(Boolean.toString(userRCYes == true || userRCNo == false));
                stLabel.setText(Boolean.toString(userSTYes == true || userSTNo == false));
                
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.addRow(new Object[]{TotalCostLabel.getText(), quantityLabel3.getText(), 
                rbLabel.getText(), rcLabel.getText(), stLabel.getText()});
            }
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog (null, "invalid user input. Integer input required");              
        }                      

        
    }//GEN-LAST:event_totalCostActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_submitActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_quitActionPerformed

    private void widthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthKeyTyped
        char input = evt.getKeyChar();
            if(!(Character.isDigit(input) || input == KeyEvent.VK_BACK_SPACE) 
                        || input == KeyEvent.VK_DELETE){
                            JOptionPane.showMessageDialog(null, "Please enter a width betwen 5 and 500.");
                    evt.consume();} // consumed means it will not be typed
    }//GEN-LAST:event_widthKeyTyped

    private void lengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lengthKeyTyped
         char input = evt.getKeyChar();
                if(!(Character.isDigit(input) || input == KeyEvent.VK_BACK_SPACE) 
                        || input == KeyEvent.VK_DELETE){
                            JOptionPane.showMessageDialog(null, "Please enter a length betwen 5 and 500.");
                    evt.consume();} 
    }// consumed means it will not be typed    }//GEN-LAST:event_lengthKeyTyped

    private void quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyTyped
         char input = evt.getKeyChar();
                if(!(Character.isDigit(input) || input == KeyEvent.VK_BACK_SPACE) 
                        || input == KeyEvent.VK_DELETE){
                            JOptionPane.showMessageDialog(null, "Please enter 1 or more quantity.");
                    evt.consume();} // consumed means it will not be typed
    }//GEN-LAST:event_quantityKeyTyped

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void heightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightKeyTyped
         char input = evt.getKeyChar();
                if(!(Character.isDigit(input) || input == KeyEvent.VK_BACK_SPACE) 
                        || input == KeyEvent.VK_DELETE){
                            JOptionPane.showMessageDialog(null, "Please enter a height betwen 5 and 500.");
                    evt.consume();}
    }// consumed means it will not be typed    }//GEN-LAST:event_heightKeyTyped

    private void boxType5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxType5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxType5ActionPerformed

    private void boxType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxType1ActionPerformed

    
    /**
     * @param cardGrade
     * @param colourType
     * @param reinBottom
     * @param reinCorner
     * @return 
     */
    public int getBoxType(int cardGrade, int colourType, boolean reinBottom, boolean reinCorner) {
        int boxType = 0;

        for (BoxTypes box: boxes) {
            if(box.hasCardGrade (cardGrade) && box.getColourType() == colourType
                    && box.hasReinBottom() == reinBottom 
                    && box.hasReinCorner() == reinCorner) {
                boxType = box.getBoxType();
                break;
            }
        }
        
        return boxType;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdditionalFuncLabel;
    private javax.swing.JLabel BoxTypeLabel;
    private javax.swing.ButtonGroup BoxTypes;
    private javax.swing.ButtonGroup ColouType;
    private javax.swing.JLabel FlexBoxTitleLabe;
    private javax.swing.JLabel Order1Label;
    private javax.swing.JLabel OrderDetailsLabel;
    private javax.swing.JLabel OrderDetailsLabel1;
    private javax.swing.JLabel OrderDetailsLabel2;
    private javax.swing.JLabel OrderShow1;
    private javax.swing.JLabel ReinBottom;
    private javax.swing.ButtonGroup ReinForcedBottom;
    private javax.swing.ButtonGroup ReinforcedCorner;
    private javax.swing.JLabel ST;
    private javax.swing.ButtonGroup SealTop;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JLabel TotalCostLabel;
    private javax.swing.JLabel TotalCostLabel1;
    private javax.swing.JRadioButton boxType1;
    private javax.swing.JRadioButton boxType2;
    private javax.swing.JRadioButton boxType3;
    private javax.swing.JRadioButton boxType4;
    private javax.swing.JRadioButton boxType5;
    private javax.swing.JRadioButton colourType0;
    private javax.swing.JRadioButton colourType1;
    private javax.swing.JRadioButton colourType2;
    private javax.swing.JLabel colourTypeLabel;
    private javax.swing.JTextField height;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField length;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JTextField quantity;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityLabel1;
    private javax.swing.JPanel quantityLabel2;
    private javax.swing.JLabel quantityLabel3;
    private javax.swing.JButton quit;
    private javax.swing.JLabel rbLabel;
    private javax.swing.JLabel rcLabel;
    private javax.swing.JLabel reinBottomLabel;
    private javax.swing.JLabel reinCorner;
    private javax.swing.JLabel reinCornerLabel;
    private javax.swing.JRadioButton reinforcedBottomNo;
    private javax.swing.JRadioButton reinforcedBottomYes;
    private javax.swing.JRadioButton reinforcedCornerNo;
    private javax.swing.JRadioButton reinforcedCornerYes;
    private javax.swing.JLabel sealTopLabel;
    private javax.swing.JRadioButton sealTopNo;
    private javax.swing.JRadioButton sealTopYes;
    private javax.swing.JLabel stLabel;
    private javax.swing.JButton submit;
    private javax.swing.JTable table;
    private javax.swing.JButton totalCost;
    private javax.swing.JTextField width;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables
}
